### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by freed00m** [trikita/talalarmo#2]
Hi, I have absolutely love the looks of the app, however the app only vibrates with no sound. I have tried multiple .mp3 files and .ogg music files ( I ca check a known working sample if you would provide ).

The device plays mp3 or ogg files normaly in VLC player. All possible volume leves were maxed out with Volume Controls app in app store to rule out the possibility on user failure.

The device is android 4.1 Lenovo A760.  I have been selecting the music with amaze file manager. I don't see any change in the settings, (maybe the path provided by amaze file manager was wrong), however I can't tell cause I don't know if there is a path/filename shown in the settings after the music have been selected.

The version is 3.5

In contrass, Alarm Klock functions properly.

Is there a debug build I can try?

**Comment by l2dy** [comment]
The bug is that Talalarmo didn't ask for storage permission.
`DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media/*** from pid=*****, uid=***** requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()`

**Comment by l2dy** [comment]
My test build.

[talalarmo-release.apk.zip](https://github.com/trikita/talalarmo/files/367829/talalarmo-release.apk.zip)
